### ISSUE TITLE
Problem parsing time-string "Igår kl 10:03"

### ISSUE THREAD

**Issue by leiflundgren** [leiflundgren/sr-fetch#10]
2018-10-16T18:57:12.636054+00:00 app[web.1]: 18:57:12: sr_helpers: parse_sr_time_string(Igår kl 10:03)
2018-10-16T18:57:12.636137+00:00 app[web.1]: 18:57:12: SrFeed: Exception handling call: , local variable 'days' referenced before assignment
2018-10-16T18:57:12.636191+00:00 app[web.1]: 18:57:12: SrFeed: yada yada
2018-10-16T18:57:12.636497+00:00 app[web.1]: 18:57:12: SrFeed: 
2018-10-16T18:57:12.636498+00:00 app[web.1]:    Traceback (most recent call last):
2018-10-16T18:57:12.636499+00:00 app[web.1]: 
2018-10-16T18:57:12.636500+00:00 app[web.1]:      File "/app/sr_feed_app.py", line 138, in application
2018-10-16T18:57:12.636502+00:00 app[web.1]:     feed_data = feeder.get_feed().encode()
2018-10-16T18:57:12.636503+00:00 app[web.1]: 
2018-10-16T18:57:12.636504+00:00 app[web.1]:      File "/app/sr_feed.py", line 79, in get_feed
2018-10-16T18:57:12.636505+00:00 app[web.1]:     (format, feed_et) = self.handle_feed_url(self.feed_url)
2018-10-16T18:57:12.636506+00:00 app[web.1]: 
2018-10-16T18:57:12.636507+00:00 app[web.1]:      File "/app/sr_feed.py", line 134, in handle_feed_url
2018-10-16T18:57:12.636508+00:00 app[web.1]:     return self.handle_feed_url(u_thing.geturl(), u_thing)
2018-10-16T18:57:12.636509+00:00 app[web.1]: 
2018-10-16T18:57:12.636511+00:00 app[web.1]:      File "/app/sr_feed.py", line 146, in handle_feed_url
2018-10-16T18:57:12.636512+00:00 app[web.1]:     return self.parse_html_feed()
2018-10-16T18:57:12.636513+00:00 app[web.1]: 
2018-10-16T18:57:12.636514+00:00 app[web.1]:      File "/app/sr_feed.py", line 275, in parse_html_feed
2018-10-16T18:57:12.636515+00:00 app[web.1]:     episodes = page_parser.episodes()
2018-10-16T18:57:12.636516+00:00 app[web.1]: 
2018-10-16T18:57:12.636517+00:00 app[web.1]:      File "/app/sr_prog_page.py", line 458, in episodes
2018-10-16T18:57:12.636518+00:00 app[web.1]:     self.find_episodes()
2018-10-16T18:57:12.636519+00:00 app[web.1]: 
2018-10-16T18:57:12.636521+00:00 app[web.1]:      File "/app/sr_prog_page.py", line 454, in find_episodes
2018-10-16T18:57:12.636522+00:00 app[web.1]:     return self.parse_page()
2018-10-16T18:57:12.636523+00:00 app[web.1]: 
2018-10-16T18:57:12.636524+00:00 app[web.1]:      File "/app/sr_prog_page.py", line 353, in parse_page
2018-10-16T18:57:12.636525+00:00 app[web.1]:     avsnitt = self.parse_episode(div, html_timestamp)
2018-10-16T18:57:12.636526+00:00 app[web.1]: 
2018-10-16T18:57:12.636527+00:00 app[web.1]:      File "/app/sr_prog_page.py", line 406, in parse_episode
2018-10-16T18:57:12.636528+00:00 app[web.1]:     avsnitt_timestamp = parse_find_transmit_time(div, html_timestamp)
2018-10-16T18:57:12.636529+00:00 app[web.1]: 
2018-10-16T18:57:12.636530+00:00 app[web.1]:      File "/app/sr_prog_page.py", line 54, in parse_find_transmit_time
2018-10-16T18:57:12.636531+00:00 app[web.1]:     return sr_helpers.parse_sr_time_string(txt, date_today)
2018-10-16T18:57:12.636533+00:00 app[web.1]: 
2018-10-16T18:57:12.636534+00:00 app[web.1]:      File "/app/sr_helpers.py", line 169, in parse_sr_time_string
2018-10-16T18:57:12.636535+00:00 app[web.1]:     days-=1
2018-10-16T18:57:12.636536+00:00 app[web.1]: 
2018-10-16T18:57:12.636539+00:00 app[web.1]:    UnboundLocalError: local variable 'days' referenced before assignment

**Comment by leiflundgren** [comment]
fixed
