### ISSUE TITLE
Hemväg program causes error

### ISSUE THREAD

**Issue by leiflundgren** [leiflundgren/sr-fetch#9]
Issue accessing
http://sr-feed.herokuapp.com/feed?tracelevel=5;format=rss&programid=4426&source=html

2018-02-14T16:23:39.429707+00:00 app[web.1]: 16:23:39: SrFeed: Failed to get tracelevel from args. Using level 3, invalid literal for int() with base 10: '5;format=rss'
2018-02-14T16:23:39.429777+00:00 app[web.1]: 16:23:39: SrFeed: creating SrFeed tracelevel=3
2018-02-14T16:23:39.435839+00:00 app[web.1]: 16:23:39: SrFeed: tracelevel is 3 request from 10.81.169.74
2018-02-14T16:23:39.438735+00:00 app[web.1]: 16:23:39: SrFeed: request.url: http://sr-feed.herokuapp.com/
2018-02-14T16:23:39.442223+00:00 app[web.1]: 16:23:39: SrFeed: base_url = http://sr-feed.herokuapp.com/   app_url=http://sr-feed.herokuapp.com/feed
2018-02-14T16:23:39.442564+00:00 app[web.1]: 16:23:39: SrFeed: Attempt to find prog=4426, proxy_data = False from http://sverigesradio.se/sida/avsnitt?programid=4426 only_episode_with_attachments=True
2018-02-14T16:23:39.443907+00:00 app[web.1]: 16:23:39: SrFeed: initaialed a feed reader for http://sverigesradio.se/sida/avsnitt?programid=4426
2018-02-14T16:23:39.444026+00:00 app[web.1]: 16:23:39: SrFeed: lxml version is , 4, 1, 1, 0
2018-02-14T16:23:39.444130+00:00 app[web.1]: 16:23:39: SrFeed: Handling url http://sverigesradio.se/sida/avsnitt?programid=4426
2018-02-14T16:23:39.444227+00:00 app[web.1]: 16:23:39: SrFeed: Fetching content from url
2018-02-14T16:23:40.263500+00:00 app[web.1]: 16:23:40: SrFeed: Urllib automatically redirected to http://sverigesradio.se/p2pahemvag
2018-02-14T16:23:40.263553+00:00 app[web.1]: 16:23:40: SrFeed: Handling url http://sverigesradio.se/p2pahemvag
2018-02-14T16:23:40.265162+00:00 app[web.1]: 16:23:40: SrFeed: Got response 200 Content-type: text/html; charset=utf-8
2018-02-14T16:23:40.265281+00:00 app[web.1]: 16:23:40: SrFeed: Retreiving content from http://sverigesradio.se/p2pahemvag
2018-02-14T16:23:40.408187+00:00 app[web.1]: 16:23:40: SrFeed: Successfully parsed urllib-response directly to xml
2018-02-14T16:23:40.408323+00:00 app[web.1]: 16:23:40: SrProgramPageParser: html_dom is _ElementTree
2018-02-14T16:23:40.409355+00:00 app[web.1]: 16:23:40: parse_datetime(2018-02-14 17:21:46)
2018-02-14T16:23:40.448974+00:00 app[web.1]: 16:23:40: SrProgramPageParser: When parsing avsnitt 1024121, failed to find timestamp
2018-02-14T16:23:40.450650+00:00 app[web.1]: 16:23:40: SrFeed: Exception handling call: , Bad parse-data
2018-02-14T16:23:40.450741+00:00 app[web.1]: 16:23:40: SrFeed: yada yada
2018-02-14T16:23:40.451155+00:00 app[web.1]: 16:23:40: SrFeed: 
2018-02-14T16:23:40.451158+00:00 app[web.1]:    Traceback (most recent call last):
2018-02-14T16:23:40.451160+00:00 app[web.1]: 
2018-02-14T16:23:40.451162+00:00 app[web.1]:      File "/app/sr_feed_app.py", line 138, in application
2018-02-14T16:23:40.451164+00:00 app[web.1]:     feed_data = feeder.get_feed().encode()
2018-02-14T16:23:40.451166+00:00 app[web.1]: 
2018-02-14T16:23:40.451167+00:00 app[web.1]:      File "/app/sr_feed.py", line 79, in get_feed
2018-02-14T16:23:40.451169+00:00 app[web.1]:     (format, feed_et) = self.handle_feed_url(self.feed_url)
2018-02-14T16:23:40.451171+00:00 app[web.1]: 
2018-02-14T16:23:40.451172+00:00 app[web.1]:      File "/app/sr_feed.py", line 134, in handle_feed_url
2018-02-14T16:23:40.451174+00:00 app[web.1]:     return self.handle_feed_url(u_thing.geturl(), u_thing)
2018-02-14T16:23:40.451176+00:00 app[web.1]: 
2018-02-14T16:23:40.451177+00:00 app[web.1]:      File "/app/sr_feed.py", line 146, in handle_feed_url
2018-02-14T16:23:40.451179+00:00 app[web.1]:     return self.parse_html_feed()
2018-02-14T16:23:40.451180+00:00 app[web.1]: 
2018-02-14T16:23:40.451182+00:00 app[web.1]:      File "/app/sr_feed.py", line 275, in parse_html_feed
2018-02-14T16:23:40.451183+00:00 app[web.1]:     episodes = page_parser.episodes()
2018-02-14T16:23:40.451185+00:00 app[web.1]: 
2018-02-14T16:23:40.451186+00:00 app[web.1]:      File "/app/sr_prog_page.py", line 312, in episodes
2018-02-14T16:23:40.451188+00:00 app[web.1]:     self.find_episodes()
2018-02-14T16:23:40.451189+00:00 app[web.1]: 
2018-02-14T16:23:40.451191+00:00 app[web.1]:      File "/app/sr_prog_page.py", line 308, in find_episodes
2018-02-14T16:23:40.451193+00:00 app[web.1]:     return self.parse_page()
2018-02-14T16:23:40.451194+00:00 app[web.1]: 
2018-02-14T16:23:40.451196+00:00 app[web.1]:      File "/app/sr_prog_page.py", line 289, in parse_page
2018-02-14T16:23:40.451197+00:00 app[web.1]:     self.validate_episodes()
2018-02-14T16:23:40.451199+00:00 app[web.1]: 
2018-02-14T16:23:40.451201+00:00 app[web.1]:      File "/app/sr_prog_page.py", line 300, in validate_episodes
2018-02-14T16:23:40.451202+00:00 app[web.1]:     raise ValueError('Bad parse-data')
2018-02-14T16:23:40.451204+00:00 app[web.1]: 
2018-02-14T16:23:40.451236+00:00 app[web.1]:    ValueError: Bad parse-data
2018-02-14T16:23:40.451328+00:00 app[web.1]: 16:23:40: SrFeed: Going to print error message, 500, Exception handling call, please review logs.
2018-02-14T16:23:40.452327+00:00 app[web.1]: 10.81.169.74 - - [14/Feb/2018 16:23:40] "GET /feed?tracelevel=5;format=rss&programid=4426&source=html HTTP/1.1" 200 -
2018-02-14T16:23:40.455773+00:00 heroku[router]: at=info method=GET path="/feed?tracelevel=5;format=rss&programid=4426&source=html" host=sr-feed.herokuapp.com request_id=41f964d7-0443-4030-b312-39c5c53355f1 fwd="62.20.95.98" dyno=web.1 connect=1ms service=1028ms status=200 bytes=2060 protocol=http

**Comment by leiflundgren** [comment]
Handled
